"""Generate matching CPU/shader glass definitions. Existing IDs must retain their meaning."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
FAMILY = HERE.parents[2]

def generate():
    palette = json.loads((HERE / 'glass-palette.json').read_text())
    entries = palette['entries']
    assert len({m['id'] for m in entries}) == len(entries)
    assert all(0 < m['id'] < 256 for m in entries)
    cs = ['// Generated by Caelix/Tools~/RawColor/generate_palette.py.', 'using Unity.Mathematics;',
          'namespace Caelix {', 'public readonly struct PackedGlassMaterial {',
          'public readonly float3 Tint;', 'public readonly float Ior, Extinction, Smoothness;',
          'public PackedGlassMaterial(float3 tint, float ior, float extinction, float smoothness) {',
          'Tint = tint; Ior = ior; Extinction = extinction; Smoothness = smoothness;', '}', '}',
          'public static class SharedGlassPalette {', 'public static PackedGlassMaterial Get(uint id) {', 'switch (id) {']
    hlsl = ['// Generated by Tools~/RawColor/generate_palette.py.', '#ifndef CAELIX_SHARED_GLASS',
            '#define CAELIX_SHARED_GLASS', 'static VoxelMaterial GetSharedGlass(uint id) {',
            'VoxelMaterial m;', 'm.albedo = 1; m.emission = 0; m.smoothness = 1; m.metallic = 0;',
            'm.IOR = 1; m.extinction = 0;', 'switch (id) {']
    for m in entries:
        tint = ', '.join(str(float(x)) for x in m['tint'])
        vals = [*m['tint'], m['ior'], m['extinction'], m['smoothness']]
        assert all(x >= 0 for x in vals)
        cs.append(f"case {m['id']}: return new PackedGlassMaterial(new float3({tint.replace(', ', 'f, ')}f), {m['ior']}f, {m['extinction']}f, {m['smoothness']}f); // {m['name']}")
        hlsl.append(f"case {m['id']}: m.albedo = float3({tint}); m.IOR = {m['ior']}; m.extinction = {m['extinction']}; m.smoothness = {m['smoothness']}; break; // {m['name']}")
    cs += ['default: return new PackedGlassMaterial(new float3(1), 1, 0, 1);', '}', '}', '}', '}']
    hlsl += ['}', 'return m;', '}', '#endif']
    (FAMILY/'Caelix-Core/Runtime/SharedGlassPalette.cs').write_text('\n'.join(cs)+'\n')
    (FAMILY/'Caelix/Runtime/Rendering/Shaders/def/CaelixSharedGlass.hlsl').write_text('\n'.join(hlsl)+'\n')

if __name__ == '__main__': generate()
